# Generated by Django 5.2.4 on 2025-09-07 13:29

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_user_current_branch'),
        ('preview', '0004_repositoryfile_file_type_repositoryfile_size_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('chunk_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preview.repositoryfile')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repo_id'], name='aihub_codee_repo_id_07f02c_idx'), models.Index(fields=['file_path'], name='aihub_codee_file_pa_4b8336_idx')],
                'unique_together': {('repo_id', 'file_path', 'chunk_id')},
            },
        ),
    ]
