# Generated by Django 5.2.4 on 2025-09-07 15:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
