# Generated by Django 5.2.4 on 2025-07-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_oauthstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryCodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(blank=True, help_text='Git commit hash', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch associated with this code state', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_states', to='accounts.branch')),
                ('repository', models.ForeignKey(help_text='The repository this code state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='code_states', to='accounts.repository')),
            ],
            options={
                'unique_together': {('repository', 'commit_hash')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript')], max_length=10)),
                ('content', models.TextField()),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of the file')),
                ('is_latest', models.BooleanField(default=True, help_text='Is this the latest version of this file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_state', models.ForeignKey(help_text='The code state this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='preview.repositorycodestate')),
            ],
            options={
                'indexes': [models.Index(fields=['file_type'], name='preview_rep_file_ty_55989e_idx'), models.Index(fields=['file_name'], name='preview_rep_file_na_166088_idx'), models.Index(fields=['file_path', 'is_latest'], name='preview_rep_file_pa_6f7c87_idx')],
                'unique_together': {('code_state', 'file_path', 'version')},
            },
        ),
    ]
