# Generated by Django 5.2.4 on 2025-08-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_current_branch"),
        ("preview", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repositorycodestate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="repositoryfile",
            name="preview_rep_file_ty_55989e_idx",
        ),
        migrations.RemoveIndex(
            model_name="repositoryfile",
            name="preview_rep_file_na_166088_idx",
        ),
        migrations.RemoveIndex(
            model_name="repositoryfile",
            name="preview_rep_file_pa_6f7c87_idx",
        ),
        migrations.RenameField(
            model_name="repositoryfile",
            old_name="file_path",
            new_name="path",
        ),
        migrations.AddField(
            model_name="repositorycodestate",
            name="commit_sha",
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="repositorycodestate",
            unique_together={("repository", "branch", "commit_sha")},
        ),
        migrations.AlterUniqueTogether(
            name="repositoryfile",
            unique_together={("code_state", "path")},
        ),
        migrations.AddField(
            model_name="repositorycodestate",
            name="is_initial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repositoryfile",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("added", "Added"),
                    ("modified", "Modified"),
                    ("removed", "Removed"),
                    ("unchanged", "Unchanged"),
                ],
                default="unchanged",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repositoryfile",
            name="is_binary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="repositoryfile",
            index=models.Index(fields=["path"], name="preview_rep_path_452730_idx"),
        ),
        migrations.RemoveField(
            model_name="repositorycodestate",
            name="commit_hash",
        ),
        migrations.RemoveField(
            model_name="repositoryfile",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="repositoryfile",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="repositoryfile",
            name="is_latest",
        ),
        migrations.RemoveField(
            model_name="repositoryfile",
            name="size_bytes",
        ),
        migrations.RemoveField(
            model_name="repositoryfile",
            name="version",
        ),
    ]
