# Generated by Django 5.2.4 on 2025-08-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0002_alter_repositorycodestate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
