# Generated by Django 5.2.4 on 2025-08-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0003_alter_repositoryfile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
