# Generated by Django 5.2.4 on 2025-09-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_current_branch'),
        ('preview', '0004_repositoryfile_file_type_repositoryfile_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='repository',
            field=models.ForeignKey(help_text='The repository this file belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.repository'),
        ),
    ]
