# Generated by Django 5.2.4 on 2025-07-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='telegram_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
