# Generated by Django 5.2.4 on 2025-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_oauthstate_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
