# Generated by Django 5.2.4 on 2025-07-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_repository_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
