# Generated by Django 5.2.4 on 2025-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_repository_pushed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.BigIntegerField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
