# Generated by Django 5.2.4 on 2025-07-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_github_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
