# Generated by Django 5.2.4 on 2025-07-26 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='accounts.repository'),
        ),
    ]
