# Generated by Django 5.2.4 on 2025-07-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_selected_repo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user', 'repo_id')},
        ),
    ]
