# Generated by Django 5.2.4 on 2025-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_repository_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('user', 'repo_id'), name='unique_user_repo'),
        ),
    ]
