# Generated by Django 5.2.4 on 2025-07-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_repository_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='repository',
            name='unique_user_repo',
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('user', 'repo_id')},
        ),
    ]
