# Generated by Django 5.2.4 on 2025-07-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_repository_unique_user_repo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_id',
            field=models.BigIntegerField(),
        ),
    ]
