# Generated by Django 5.2.4 on 2025-07-31 16:58

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_repository_repo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
