# Generated by Django 5.2.4 on 2025-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
